export const SAVE_ALL_COUNTRIES_API = 'SAVE_ALL_COUNTRIES_API';
export const SEARCH_COUNTRY_RESULTS = 'SEARCH_COUNTRY_RESULTS';
export const SEARCH_COUNTRY_NAME = 'SEARCH_COUNTRY_NAME';
export const SELECT_COUNTRY_INFO = 'SELECT_COUNTRY_INFO';