export const THEME_COLOR = 'THEME_COLOR';
export const SAVE_ALL_COUNTRIES_API = 'SAVE_ALL_COUNTRIES_API';
export const SEARCH_COUNTRY_RESULTS = 'SEARCH_COUNTRY_RESULTS';
export const SEARCH_COUNTRY_NAME = 'SEARCH_COUNTRY_NAME';
export const SEARCH_COUNTRY_BY_REGION = 'SEARCH_COUNTRY_BY_REGION';